<?php
$_categoryId = 42;
$_productCollection = Mage::getModel('catalog/category')->load($_categoryId)
    ->getProductCollection()->addAttributeToSelect('*')->setPageSize(10);
?>
<?php if(!true): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php foreach ($_productCollection as $_product): ?>
            <div class="item">
                <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                </a>

                <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>

                <?php echo $this->getPriceHtml($_product, true) ?>
            </div>
        <?php endforeach ?>
    </div>
<?php endif; ?>