<?php
$collection = Mage::getModel('catalog/product')->getCollection();
$collection->addAttributeToFilter('refubrished',true);
$_productCollection = $collection->addAttributeToSelect('*');
?>

<div id="slideshow_refubrished" class="owl-carousel" style="opacity: 1;">
    <?php foreach ($_productCollection as $_product): ?>
        <div class="item">
            <a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="img-responsive" /></a>
        </div>
    <?php endforeach ?>
</div>
<p><a href="<?php echo $this->getUrl('mymod/view/viewrefubrished') ?>"><?php echo  $this->__('Explore all Refubrished'); ?></a></p>
<script type="text/javascript"><!--
    jQuery('#slideshow_refubrished').owlCarousel({
        items: 6,
        autoPlay: 3000,
        navigation: true,
        navigationText: ['<i class="fa fa-chevron-left fa-5x"></i>', '<i class="fa fa-chevron-right fa-5x"></i>'],
        pagination: true
    });
    --></script>